import type { Metadata } from "next";

import { ThemeStoreProvider } from "@/providers/theme";
import Body from "@/components/Body";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
    return (
        <ThemeStoreProvider>
            <Body>{children}</Body>
        </ThemeStoreProvider>
    );
}
