import type { Metadata } from "next";
import { Montserrat, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const ibmMono = IBM_Plex_Mono({
    variable: "--font-ibm-mono",
    weight: "400",
    subsets: ["latin"],
});

const montserratSans = Montserrat({
    variable: "--font-montserrat-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${ibmMono.variable} ${montserratSans.variable}`}>
                {children}
            </body>
        </html>
    );
}
